"use client";

import { EvidenceAppendix } from "@/components/EvidenceAppendix";
import { EvidenceRecord } from "@/lib/evidence";

export function NarrativeReport({
  narrative,
  evidence,
  loading,
}: {
  narrative: string | null;
  evidence: EvidenceRecord[];
  loading: boolean;
}) {
  if (loading) {
    return (
      <div className="panel report-card">
        <div className="meta"><span className="spinner" />Agent is narrating the trace…</div>
      </div>
    );
  }
  if (!narrative) return null;

  return (
    <div className="panel report-card">
      <div className="report-header">
        <div className="report-title">Investigation narrative</div>
        <div className="report-timestamp">generated by agent</div>
      </div>
      <div className="narrative">{narrative}</div>
      <EvidenceAppendix evidence={evidence} />
    </div>
  );
}
